---  # Add document start marker
baseURL: "https://hoogvliets.github.io/personal-website"
languageCode: en-us
title: Raphaël Hoogvliets
theme: ["PaperMod"]
pagination.pagerSize: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-QMM8X7W17D

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production    # Fixed comment spacing
  title: Raphaël Hoogvliets
  description: "Personal website of Raphaël Hoogvliets"
  keywords: [Blog, Services, Portfolio, Personal Website, PaperMod]
  author: Raphaël Hoogvliets
  # author: ["Me", "You"]    # Fixed comment spacing
  images: [
    "<link or path of image for opengraph, twitter-cards>"
  ]
  DateFormat: "January 2, 2006"
  defaultTheme: auto  # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true    # Fixed comment spacing
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Raphaël Hoogvliets"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false  # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: about me
        url: /about-me/
      - name: MLOps
        url: /mlops/

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B\U0001F3FD"
    Content: Welcome to my personal website!

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/hoogvliets/"
    - name: substack
      url: "https://mettlesome.substack.com/"
    - name: medium
      url: "https://medium.com/@hoogvliets"
    - name: spotify
      url: "https://open.spotify.com/show/3d6X8Yjn41AXjrmhCwMSHN?si=6f7042387b09444e"
    - name: youtube
      url: "https://www.youtube.com/@hoogvliets"
    - name: tiktok
      url: "https://www.tiktok.com/@hoogvliets"
    - name: instagram
      url: "https://www.instagram.com/config.yaml/"
    - name: gitlab
      url: "https://gitlab.com/hoogvliets"
    - name: github
      url: "https://github.com/hoogvliets"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"    # Fixed comment spacing
    bing:
      SiteVerificationTag: "XYZabc"    # Fixed comment spacing
    yandex:
      SiteVerificationTag: "XYZabc"    # Fixed comment spacing

  cover:
    hidden: true    # Fixed comment spacing
    hiddenInList: true    # Fixed comment spacing
    hiddenInSingle: true  # hide on single page

  editPost:
    URL: "https://github.com/hoogvliets/personal-website/tree/main/content"
    Text: "Suggest Changes"    # Fixed comment spacing
    appendFilePath: true    # Fixed comment spacing

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false    # Fixed comment spacing
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10  # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

  social:
    github: "hoogvliets"
    linkedin: "hoogvliets"
    instagram: "hoogvliets"
    tiktok: "hoogvliets"


menu:
  main:
    - identifier: about-me
      name: about me
      url: /about-me/
      weight: 10
    - identifier: mentorship
      name: mentorship
      url: /mentorship/
      weight: 20
    - identifier: mlops
      name: MLOps
      url: /mlops/
      weight: 30
    - identifier: blog
      name: blog
      url: https://mettlesome.substack.com/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai


module.mounts:    # Added colon to define the key properly
  source: 'images'
  target: 'static/images'
